import Head from 'next/head'
import { useEffect } from 'react'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {


  useEffect(() => {
    async function getPosts() {
      const res = await fetch(process.env.NEXT_PUBLIC_API_URL)
      const data = await res.json()

      console.log(data)
    }

    getPosts()
  }, [])
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h2>Hello world let run this</h2>
    </div>
  )
}
